### ISSUE TITLE
Bessere Scans, auch für die DTA-Ausgaben: (wo & wie?) vermerken?

### ISSUE THREAD

**Issue by cthomasdta** [avh-bern-berlin/avh-texts#32]
> Also better copy of original here. But where is the most convenient place to upload these files for DTA to use?
> 
> [humboldt_verhandeling_1790 BESSER.pdf](https://github.com/avh-bern-berlin/avh-texts/files/9172223/humboldt_verhandeling_1790.BESSER.pdf)

@haoess schöne Scans, aber diese für alle, die Rex findet, auszutauschen, kann DTA nicht mehr leisten, oder?

@rexclark2 in any case you should list the source of better scans *additionally* to the DTA URL in the Bern files, if the source seems trustworthy. That would be great!

_Originally posted by @cthomasdta in https://github.com/avh-bern-berlin/avh-texts/issues/31#issuecomment-1193082292_

**Comment by thomasnehrlich** [comment]
@rexclark2 Vielen Dank für Deine Suche nach besseren Scans! Wo legst Du die neuen Scans ab? Zum Beispiel in der Dropbox, damit ich sie in unser Archiv aufnehmen kann?

**Comment by rexclark2** [comment]
Seems like best way to handle this is:

I will add the URL for reliable source to the google sheet for the project, at some point we can update all of these at one time for the Bern headers. My go-to source for better scans is HathiTrust Digital Library, will attempt if I can to have URL that targets the first page of our text, instead of the whole work.

@thomasnehrlich Yes, I'll put a file in the existing folder 'add to PDFs gesamt' in 'Bibliographie' (please rename or move as needed if it makes more sense). These will be only the pages needed, so could also at some point  be used to update at one time all of the DTA files if time available.
