### ISSUE TITLE
Cyanometer: Wirklich erst 1798 erfunden?!

### ISSUE THREAD

**Issue by cthomasdta** [avh-bern-berlin/avh-texts#41]
https://humboldt.unibe.ch/erschliessung/instrumente_und_medien, **Cyanometer**: 

> Entwickelt 1798 von [Horace-Bénédict de Saussure](http://d-nb.info/gnd/118804790).
> […]
> Humboldt führte bei seiner Südamerikareise ein Cyanometer mit, das er 1798 in Paris erworben hatte.

Woher stammt die Angabe, dass Saussure das erst 1798 entwickelt hat?

Es müsste jedenfalls schon früher, (spätestens) 1787 bei Besteigung des Mont Blanc (mit Rast am Col du Géant) dabei gewesen sein!  Vielleicht habt ihr versehentlich dieselbe Jahreszahl für die Erfindung wie für die spätere Erwerbung eines Cyanometers durch Humboldt angesetzt?

**Comment by rexclark2** [comment]
Yes, thanks for catching this, I think this was possibly a transposition error since many references date the cyanometer from this 1789 article: Description d'un cyanomètre ou d'un appareil destiné à mesurer l'intensité de la couleur bleue du ciel, in: Mémoires de l'Academie Royale Des Sciences aTurin 1788-1789 (1790), 409-424.  A nice photo of the original illustration on google books:
https://www.google.com/books/edition/Memoires_de_l_Academie_royale_des_scienc/rKlKKz7uJowC?hl=en&gbpv=1&pg=PA425&printsec=frontcover

But as you state, Saussure had an earlier version, apparently with only 16 shades of blue, in 1787 on Mont Blanc.  A good history of the cyanometer in general I think is this article:
Himmelblau-das Cyanometer des "Horace-Bénédict de Saussure" (1740–1799) Author(s): Olaf Breidbach and André Karliczek, Sudhoffs Archiv , 2011, Bd. 95, H. 1 (2011), pp. 3-29.
https://www.jstor.org/stable/23078587

Long and short of this is I’m correcting text to "Entwickelt 1787”

**Comment by thomasnehrlich** [comment]
Vielen Dank!
